from .models import Cube


DEMO_PROBLEMS = [
    {
        "id": "cube-view-001",
        "revision_id": "cube-view-001-r1",
        "title": "起始题：从正面看到了什么",
        "statement": "用 4 个同样大小的小正方体摆成图示组合体。先观察模型，不要拆动。",
        "question": "从正面看，画出的平面图形是什么样的？说明哪些小正方体在视线方向上发生了重合。",
        "answer": "正面图有两列：左列高 1 格，右列高 2 格；右下位置有 2 个小正方体沿视线方向重合。",
        "teaching_role": "建立方法",
        "difficulty": "基础",
        "source_label": "一朵教学原创演示题",
        "source_status": "原创待教师审核",
        "school_stage": "小学",
        "grade": 5,
        "topic": "观察物体与简单组合体",
        "concepts": ["正面图", "遮挡", "投影"],
        "methods": ["逐列观察", "固定视角"],
        "tags": ["三视图", "空间想象", "基础"],
        "purpose": "把“转动物体”和“换观察方向”联系起来，先让学生说出哪些小正方形会重合。",
        "teacher_prompt": "先不要数总块数：从正面看，哪两块会挡在同一列？为什么？",
        "teaching_note": "拖动模型后回到正视图，对照投影。强调看到的是轮廓与每列高度，不是所有方块。",
        "cubes": [
            Cube(x=0, y=0, z=0), Cube(x=1, y=0, z=0),
            Cube(x=1, y=1, z=0), Cube(x=1, y=0, z=1),
        ],
        "next": {"id": "cube-view-002", "relation": "对比", "reason": "正面图保持相同，增加上视图来区分不同摆法。"},
    },
    {
        "id": "cube-view-002",
        "revision_id": "cube-view-002-r1",
        "title": "对比题：一个视图够不够",
        "statement": "下面的组合体和上一题从正面看到的图形相同，但小正方体的前后位置不同。",
        "question": "只看正面图能唯一确定摆法吗？再选择一个观察方向，并说明怎样用它区分两种摆法。",
        "answer": "不能。可以比较上视图；上视图会保留小正方体的前后位置，因此能区分正面图相同的不同摆法。",
        "teaching_role": "对比辨析",
        "difficulty": "进阶",
        "source_label": "一朵教学原创演示题",
        "source_status": "原创待教师审核",
        "school_stage": "小学",
        "grade": 5,
        "topic": "观察物体与简单组合体",
        "concepts": ["正面图", "上视图", "信息缺失"],
        "methods": ["对比摆法", "增加视角"],
        "tags": ["三视图", "空间想象", "对比"],
        "purpose": "观察不同方向的信息损失，理解一个视图通常不能唯一确定组合体。",
        "teacher_prompt": "只给你正面图，后排的小正方体可以放在哪里而不改变它？",
        "teaching_note": "先锁定正面，再自由旋转验证猜想。让学生提出两种摆法，比较它们的上视图。",
        "cubes": [
            Cube(x=0, y=0, z=0), Cube(x=1, y=0, z=0),
            Cube(x=1, y=1, z=0), Cube(x=0, y=0, z=1),
        ],
        "next": {"id": "cube-view-003", "relation": "迁移", "reason": "从判断单个视图的信息，迁移到综合多个方向反推组合体。"},
    },
    {
        "id": "cube-view-003",
        "revision_id": "cube-view-003-r1",
        "title": "迁移题：从三个方向反推",
        "statement": "观察一个由 7 个小正方体搭成的组合体及它的正面、左面和上面投影。",
        "question": "三个方向的图分别保留了哪些信息？按什么顺序检查，才能判断模型是否同时满足三个视图？",
        "answer": "先用上视图确定底面位置，再用正面图确定左右各列最高层，用左视图检查前后各列高度；三个条件必须同时满足。",
        "teaching_role": "综合迁移",
        "difficulty": "挑战",
        "source_label": "一朵教学原创演示题",
        "source_status": "原创待教师审核",
        "school_stage": "小学",
        "grade": 5,
        "topic": "观察物体与简单组合体",
        "concepts": ["三视图", "约束", "反推"],
        "methods": ["逐项约束", "交叉检查"],
        "tags": ["空间想象", "综合", "迁移"],
        "purpose": "综合三个方向的信息，理解每个视图保留什么，以及怎样逐项检查一个组合体。",
        "teacher_prompt": "三个视图各限制了什么？先确定一定存在的方块，再讨论还有哪些位置可以补。",
        "teaching_note": "用上视图定位置、正视图定各列最高层、左视图检查前后高度。把猜测转成逐项约束。",
        "cubes": [
            Cube(x=0, y=0, z=0), Cube(x=1, y=0, z=0),
            Cube(x=2, y=0, z=0), Cube(x=0, y=0, z=1),
            Cube(x=1, y=0, z=1), Cube(x=1, y=1, z=1),
            Cube(x=2, y=1, z=0),
        ],
        "next": {"id": "cube-view-004", "relation": "同法巩固", "reason": "单独练习上视图，巩固竖直方向重合的判断。"},
    },
    {
        "id": "cube-view-004",
        "revision_id": "cube-view-004-r1",
        "title": "巩固题：画出上视图",
        "statement": "用 5 个小正方体搭成图示组合体，其中一列叠放了 2 个小正方体。",
        "question": "从上面看能看到几个方格？画出上视图，并说明叠放的一列为什么只占一个位置。",
        "answer": "上视图占 4 个方格，位置形成两行错开的形状；同一竖直列中的小正方体从上面看会重合。",
        "teaching_role": "同法巩固",
        "difficulty": "基础",
        "source_label": "一朵教学原创演示题",
        "source_status": "原创待教师审核",
        "school_stage": "小学",
        "grade": 5,
        "topic": "观察物体与简单组合体",
        "concepts": ["上视图", "竖直重合", "底面位置"],
        "methods": ["逐格投影", "忽略高度"],
        "tags": ["三视图", "空间想象", "巩固"],
        "purpose": "把上视图理解为底面位置集合，区分方块总数和上视图方格数。",
        "teacher_prompt": "哪两个小正方体从上面看落在同一个方格？高度会不会增加上视图的方格数？",
        "teaching_note": "先圈出每一根竖直柱，再把每根柱投成一个方格，最后核对位置关系。",
        "cubes": [
            Cube(x=0, y=0, z=0), Cube(x=1, y=0, z=0),
            Cube(x=1, y=1, z=0), Cube(x=1, y=0, z=1),
            Cube(x=2, y=0, z=1),
        ],
        "next": {"id": "cube-view-005", "relation": "视角迁移", "reason": "把逐格投影方法从上面迁移到左面。"},
    },
    {
        "id": "cube-view-005",
        "revision_id": "cube-view-005-r1",
        "title": "迁移题：从左面观察",
        "statement": "用 5 个小正方体搭成图示组合体，左右方向上存在重合。",
        "question": "从左面看是什么图形？指出哪个位置包含沿视线方向重合的小正方体。",
        "answer": "左视图是 2×2 的正方形；左下位置有 2 个小正方体沿左右方向重合。",
        "teaching_role": "视角迁移",
        "difficulty": "进阶",
        "source_label": "一朵教学原创演示题",
        "source_status": "原创待教师审核",
        "school_stage": "小学",
        "grade": 5,
        "topic": "观察物体与简单组合体",
        "concepts": ["左视图", "遮挡", "方向转换"],
        "methods": ["固定视角", "逐层观察"],
        "tags": ["三视图", "空间想象", "迁移"],
        "purpose": "更换观察方向，检查学生能否重新确定横向和竖向，而不是背固定图形。",
        "teacher_prompt": "转到左面后，原来的左右方向在图上还保留吗？哪个方向被压缩了？",
        "teaching_note": "先说清观察方向，再确定图上的横轴表示前后、纵轴表示高度。",
        "cubes": [
            Cube(x=0, y=0, z=0), Cube(x=0, y=1, z=0),
            Cube(x=1, y=0, z=0), Cube(x=0, y=0, z=1),
            Cube(x=0, y=1, z=1),
        ],
        "next": {"id": "cube-view-006", "relation": "反例", "reason": "通过上视图相同但高度不同的反例，认识单一视图的信息边界。"},
    },
    {
        "id": "cube-view-006",
        "revision_id": "cube-view-006-r1",
        "title": "反例题：上视图能看出高度吗",
        "statement": "组合体的上视图是一个 2×2 正方形，其中一个位置叠放了两个小正方体。",
        "question": "只看上视图，能判断每个位置有几层吗？还需要哪个方向的信息？",
        "answer": "不能。上视图只能确定占用了哪些底面位置，不能确定各位置的高度；还要结合正面图和左视图。",
        "teaching_role": "反例辨析",
        "difficulty": "进阶",
        "source_label": "一朵教学原创演示题",
        "source_status": "原创待教师审核",
        "school_stage": "小学",
        "grade": 5,
        "topic": "观察物体与简单组合体",
        "concepts": ["上视图", "高度", "信息缺失"],
        "methods": ["构造反例", "多视图验证"],
        "tags": ["三视图", "空间想象", "反例"],
        "purpose": "用反例说明上视图保留位置但丢失高度，建立多视图互补意识。",
        "teacher_prompt": "保持上视图不变，能不能把其中一列继续加高？为什么？",
        "teaching_note": "让学生先猜两种不同高度，再旋转模型比较它们的正面图或左视图。",
        "cubes": [
            Cube(x=0, y=0, z=0), Cube(x=1, y=0, z=0),
            Cube(x=0, y=0, z=1), Cube(x=1, y=0, z=1),
            Cube(x=1, y=1, z=1),
        ],
        "next": {"id": "cube-view-007", "relation": "表示转换", "reason": "从平面位置进一步读取每个位置标注的层数。"},
    },
    {
        "id": "cube-view-007",
        "revision_id": "cube-view-007-r1",
        "title": "表示题：根据层数统计方块",
        "statement": "从上面看有连续 3 个位置，三个位置上的层数依次是 1、2、3。",
        "question": "这个组合体一共有多少个小正方体？为什么不能只数上视图中的 3 个方格？",
        "answer": "共有 1+2+3=6 个小正方体。上视图方格表示位置，方格上的层数才表示该位置的小正方体个数。",
        "teaching_role": "表示转换",
        "difficulty": "基础",
        "source_label": "一朵教学原创演示题",
        "source_status": "原创待教师审核",
        "school_stage": "小学",
        "grade": 5,
        "topic": "观察物体与简单组合体",
        "concepts": ["上视图", "层数", "方块总数"],
        "methods": ["按位置求和", "图数转换"],
        "tags": ["空间想象", "计数", "表示"],
        "purpose": "区分投影位置数和立体方块总数，把带层数的上视图转换成立体数量。",
        "teacher_prompt": "上视图的一个方格代表一个方块，还是代表一根可能有多层的柱？",
        "teaching_note": "逐个位置读层数并求和，再用旋转模型核对每根柱的高度。",
        "cubes": [
            Cube(x=0, y=0, z=0),
            Cube(x=1, y=0, z=0), Cube(x=1, y=1, z=0),
            Cube(x=2, y=0, z=0), Cube(x=2, y=1, z=0), Cube(x=2, y=2, z=0),
        ],
        "next": {"id": "cube-view-008", "relation": "综合检查", "reason": "把位置、层数和多个视图合并为一套核验顺序。"},
    },
    {
        "id": "cube-view-008",
        "revision_id": "cube-view-008-r1",
        "title": "综合题：哪一个视图负责检查",
        "statement": "一个组合体已经用上视图确定底面位置，用正面图确定了左右各列的最高层。",
        "question": "左视图在最后检查什么？如果左视图不符合，说明前两步遗漏了哪类信息？",
        "answer": "左视图检查前后各列的高度。若不符合，说明前两步没有确定或错误安排了前后方向上的层数。",
        "teaching_role": "综合检查",
        "difficulty": "挑战",
        "source_label": "一朵教学原创演示题",
        "source_status": "原创待教师审核",
        "school_stage": "小学",
        "grade": 5,
        "topic": "观察物体与简单组合体",
        "concepts": ["三视图", "前后高度", "一致性"],
        "methods": ["分步核验", "错误定位"],
        "tags": ["空间想象", "综合", "检查"],
        "purpose": "让学生说明每个视图在核验中的职责，并能根据冲突定位遗漏的信息。",
        "teacher_prompt": "上视图和正面图都满足时，为什么仍可能不满足左视图？",
        "teaching_note": "要求学生逐步口述：上面定位置、正面定左右高度、左面查前后高度。",
        "cubes": [
            Cube(x=0, y=0, z=0), Cube(x=1, y=0, z=0),
            Cube(x=2, y=0, z=0), Cube(x=0, y=1, z=0),
            Cube(x=1, y=0, z=1), Cube(x=1, y=1, z=1),
            Cube(x=2, y=0, z=1),
        ],
        "next": None,
    },
]
